### ISSUE TITLE
Duplicate setList

### ISSUE THREAD

**Issue by JohnCervantes** [jodylecompte/youtube-setlist-chrome#2]
Hi Jody,

I found a bug in your awesome extension where the set list tab is showing twice. I haven't figured out what exactly is the cause, but I'll let you know if I find anything. I also have attached a screenshot of the bug. Thanks!

![image](https://user-images.githubusercontent.com/28201970/140147760-57734b87-53f3-4682-870e-e9c7a3cf0f82.png)

**Comment by jodylecompte** [comment]
This has been fixed in version 1.2 which was just published to the chrome store (pending review). Thanks for bringing this to my attention!
